# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VectorStats
                                 A QGIS plugin
 Plugin for descriptive and statistical analysis of vectors, with chart generation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-20
        copyright            : (C) 2024 by Breno Nunes
        email                : breno_1697@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VectorStats class from file VectorStats.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Stats import VectorStats
    return VectorStats(iface)
